"""init

Revision ID: 10db685d94d0
Revises: 
Create Date: 2026-04-07 19:22:24.955363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '10db685d94d0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('nama', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('nim', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('password_hashed', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('blog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('judul', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('isi', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id_creator', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_creator'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blog')
    op.drop_table('user')
    # ### end Alembic commands ###
